In [3]:
import torch
import numpy as np

In [4]:
data = [[1, 2],[4, 6],[3, 9]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [4, 6],
        [3, 9]])


In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensoer = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensoer)

tensor([[0.2159, 0.8901, 0.3639],
        [0.0187, 0.1260, 0.7857]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
tensor = torch.rand(3,4)

if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print('Device tensor is stored on: ', tensor.device)
print('Tensor: ', tensor)
print('First row: ', tensor[0])
print('First column: ', tensor[:,0])
print('Last column: ', tensor[..., -1])
print('Last row: ', tensor[-1])

Device tensor is stored on:  cpu
Tensor:  tensor([[0.9317, 0.5116, 0.5604, 0.8177],
        [0.0931, 0.1065, 0.5546, 0.9013],
        [0.8739, 0.8539, 0.8309, 0.6425]])
First row:  tensor([0.9317, 0.5116, 0.5604, 0.8177])
First column:  tensor([0.9317, 0.0931, 0.8739])
Last column:  tensor([0.8177, 0.9013, 0.6425])
Last row:  tensor([0.8739, 0.8539, 0.8309, 0.6425])


In [18]:
# -*- coding: utf-8 -*-

import torch
import math


dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
print('Input data: ', x)
y = torch.sin(x)
print('Expected Value: ', y)

# Randomly initialize weights
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights using gradient descent
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d


print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

Input data:  tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
Expected Value:  tensor([ 8.7423e-08, -3.1430e-03, -6.2863e-03,  ...,  6.2863e-03,
         3.1430e-03, -8.7423e-08])
99 460.7714538574219
199 308.1343994140625
299 207.0688018798828
399 140.1432342529297
499 95.82095336914062
599 66.46469116210938
699 47.01887512207031
799 34.13632583618164
899 25.600662231445312
999 19.944408416748047
1099 16.19572639465332
1199 13.710844039916992
1299 12.063411712646484
1399 10.97105598449707
1499 10.246603965759277
1599 9.766045570373535
1699 9.447214126586914
1799 9.235621452331543
1899 9.095175743103027
1999 9.001924514770508
Result: y = -0.003960185218602419 + 0.8440380692481995 x + 0.000683197402395308 x^2 + -0.09152352809906006 x^3
